Dev
TymekGluch/circle-and-cross pull request #1
Opened 2022-06-23 19:51 UTC by TymekGluch

adding html structure and css simple styles

2022-06-23 20:26 UTC, MarekGluch requested changes

2022-06-23 20:26 UTC, MarekGluch commented on index.html
> +                    <button id="field-1.1" class="game-board__field game-board__field--cross" disabled aria-label="field - 1.1"></button>  <!-- field - row.column -->
at the moment I have no idea if these id's will be needed

2022-06-23 20:26 UTC, MarekGluch commented on index.html
> +                <p class="footers__text">
Are you sure two paragraphs were needed here?

2022-06-23 20:26 UTC, MarekGluch commented on style.css
> +    font-weight: 900;
you only import 100 and 300 weight and here you use 900

2022-06-23 20:26 UTC, MarekGluch commented on style.css
> +
this break is not needed

2022-06-23 20:26 UTC, MarekGluch commented on style.css
> +    transition-duration: 350ms;
Always indicate which CSS property is to be animated (it is good practice to only animate transform and opacity, if possible)

2022-06-24 10:05 UTC, TymekGluch commented on index.html
> +                    <button id="field-1.1" class="game-board__field game-board__field--cross" disabled aria-label="field - 1.1"></button>  <!-- field - row.column -->
i did it

2022-06-24 10:06 UTC, TymekGluch commented on index.html
> +                <p class="footers__text">
i changed it

2022-06-24 10:12 UTC, TymekGluch commented on style.css
> +    font-family: 'Montserrat', sans-serif;
i chenged it

2022-06-24 10:13 UTC, TymekGluch commented on style.css
> +    font-weight: 900;
i changed it

2022-06-24 10:17 UTC, TymekGluch commented on style.css
> +    transition-duration: 350ms;
i changed it

2022-06-24 10:18 UTC, TymekGluch commented on style.css
> +
i changed it

2022-06-24 10:22 UTC, TymekGluch commented on style.css
> +    height: 7VH;
i changed all capital letters  to lower case

2022-06-24 10:22 UTC, TymekGluch commented on style.css
> +
i changed it

2022-06-24 11:15 UTC, GabrielGladykowski approved these changes

2022-06-24 11:35 UTC, MarekGluch approved these changes

2022-06-24 11:35 UTC, merged